### ISSUE TITLE
LoveLace to-do's

### ISSUE THREAD

**Issue by tr1plus** [tr1plus/ha-aftership#2]
As the lovelace version is still in its very early stages, find a to-do below of things I still want to achieve.
### High Priority
- [ ] add css/styling support
- [ ] add column with latest update date
- [ ] add possibility for drop-down with even more info

### Low Priority
- [ ] delete trackings from HASS
- [ ] add trackings from HASS

Comment here for more features required in lovelaceUI.

**Comment by vMeph** [comment]
any possibility to when de packages arrive to delete from HA directly?
and add packages?

**Comment by tr1plus** [comment]
updated, not sure if it will be possible but I will look into it when the rest is done :)

**Comment by vMeph** [comment]
any way to include your card into tracker-card?
https://github.com/custom-cards/tracker-card
https://github.com/custom-components/custom_updater

this way everytime you do updates into aftership card we can be notify and do the updates in 1 click :)

**Comment by tr1plus** [comment]
Not sure... I read that it is only for 
https://github.com/custom-cards
https://github.com/custom-components
https://github.com/ciotlosm/custom-lovelace

May look into it in the future but don't think I'll do this. I think I'll rather prioritize an actual hass component compared to this :)
